services:
  postgres:
    image: postgres:16.4 
    container_name: hightide_db  
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: hightide 
      POSTGRES_DB: hightide 
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:
    driver: local
